package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.47

import (
	"CommentsGQL"
	"CommentsGQL/models"
	"context"
	"fmt"
)

// CommentAdded is the resolver for the commentAdded field.
func (r *subscriptionResolver) CommentAdded(ctx context.Context, postID int) (<-chan *models.Comment, error) {
	panic(fmt.Errorf("not implemented: CommentAdded - commentAdded"))
}

// Subscription returns CommentsGQL.SubscriptionResolver implementation.
func (r *Resolver) Subscription() CommentsGQL.SubscriptionResolver { return &subscriptionResolver{r} }

func (r *Resolver) Query() CommentsGQL.QueryResolver {
	return &queryResolver{r}
}

func (r *Resolver) Mutation() CommentsGQL.MutationResolver {
	return &mutationResolver{r}
}
